version: 0.2

phases:
  pre_build:
    commands:
      - $(chmod +x pipeline/codedeploy/*.sh)
      - pipeline/codedeploy/preq.sh
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION) 
  build:
    commands:
      - echo Build started on `date`
      - pipeline/codedeploy/build_image.sh      
      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker ps
      - docker push 239144702963.dkr.ecr.AWS_REGION.amazonaws.com/cicddemo
      - printf '[{"name":"bandappcontainer","imageUri":"%s"}]' 239144702963.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest > imagedefinitions.json
      # - printf '[{"name":"bandappcontainer","imageUri":"%s"}]' 239144702963.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest > imagedefinitions.json
      - echo Build completed on `date`

artifacts:
    files: 
      - imagedefinitions.json

