version: 0.2

phases:
  pre_build:
    commands:
      - $(chmod +x pipeline/codedeploy/*.sh)
      - pipeline/codedeploy/preq.sh
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION) 
      # - export AWS_ACCOUNT_ID="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .accountId)"
      - echo "AWS_ACCOUNT_ID=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .accountId)" >>  /etc/environment
      - echo AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
  build:
    commands:
      - echo Build started on `date`
      - pipeline/codedeploy/build_image.sh      
      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - echo $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo
      - printf '[{"name":"bandappcontainer","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest > imagedefinitions.json
      # - printf '[{"name":"bandappcontainer","imageUri":"%s"}]' 239144702963.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest > imagedefinitions.json
      - echo Build completed on `date`

artifacts:
    files: 
      - imagedefinitions.json

