version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - $(chmod +x pipeline/codedeploy/*.sh)
      - pipeline/codedeploy/preq.sh
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2) 
  build:
    commands:
      - echo Build started on `date`
      - pipeline/codedeploy/build_image.sh      
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker ps
      - docker push 239144702963.dkr.ecr.us-west-2.amazonaws.com/cicddemo
      - printf '[{"name":"bandappcontainer","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
    files: 
      - imagedefinitions.json
      - appspec.yaml
